from typing import Any
from typing import List
from typing import Optional
from typing import Tuple

from .pyvcroid2 import Param

class VcRoid2:
    @property
    def param(self) -> Param: ...
    def __enter__(self) -> VcRoid2: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def listLanguages(self) -> List[str]: ...
    def loadLanguage(self, language_name: str) -> None: ...
    def listVoices(self) -> List[str]: ...
    def loadVoice(self, voice_name: str) -> None: ...
    def textToSpeech(
        self, text: str, *, timeout: Optional[float] = ..., raw: bool = ...
    ) -> Tuple[bytes, List[Any]]: ...
