from typing import Any

class Param:
    def __init__(self, default_parameter: Any, parameter: Any) -> None: ...
    @property
    def minMasterVolume(self) -> float: ...
    @property
    def maxMasterVolume(self) -> float: ...
    @property
    def defaultMasterVolume(self) -> float: ...
    @property
    def masterVolume(self) -> float: ...
    @masterVolume.setter
    def masterVolume(self, value: float) -> None: ...
    @property
    def minVolume(self) -> float: ...
    @property
    def maxVolume(self) -> float: ...
    @property
    def defaultVolume(self) -> float: ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, value: float) -> None: ...
    @property
    def minSpeed(self) -> float: ...
    @property
    def maxSpeed(self) -> float: ...
    @property
    def defaultSpeed(self) -> float: ...
    @property
    def speed(self) -> float: ...
    @speed.setter
    def speed(self, value: float) -> None: ...
    @property
    def minPitch(self) -> float: ...
    @property
    def maxPitch(self) -> float: ...
    @property
    def defaultPitch(self) -> float: ...
    @property
    def pitch(self) -> float: ...
    @pitch.setter
    def pitch(self, value: float) -> None: ...
    @property
    def minEmphasis(self) -> float: ...
    @property
    def maxEmphasis(self) -> float: ...
    @property
    def defaultEmphasis(self) -> float: ...
    @property
    def emphasis(self) -> float: ...
    @emphasis.setter
    def emphasis(self, value: float) -> None: ...
    @property
    def minPauseMiddle(self) -> float: ...
    @property
    def maxPauseMiddle(self) -> float: ...
    @property
    def defaultPauseMiddle(self) -> float: ...
    @property
    def pauseMiddle(self) -> float: ...
    @pauseMiddle.setter
    def pauseMiddle(self, value: float) -> None: ...
    @property
    def minPauseLong(self) -> float: ...
    @property
    def maxPauseLong(self) -> float: ...
    @property
    def defaultPauseLong(self) -> float: ...
    @property
    def pauseLong(self) -> float: ...
    @pauseLong.setter
    def pauseLong(self, value: float) -> None: ...
    @property
    def minPauseSentence(self) -> float: ...
    @property
    def maxPauseSentence(self) -> float: ...
    @property
    def defaultPauseSentence(self) -> float: ...
    @property
    def pauseSentence(self) -> float: ...
    @pauseSentence.setter
    def pauseSentence(self, value: float) -> None: ...
